title: Gizem Test
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://fjnn.github.io/jtd-test

aux_links:
  Template Repository: https://github.com/fjnn/jtd-test
